[package]
name = "positron-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
positron={version = "0.2.3", features= ["json"]}
rocket = {version="0.5.0-rc.1", features = ["json"]}
serde = "*"
